{application,ed25519,
             [{description,"An OTP library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[ed25519]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
